### PR TITLE
Add a `pollInterval` option to poll for updates from the logs

### PR DESCRIPTION
**Pull request by BenMusch**
I would like to occasionally poll for updates to the logs. Right now the only way to do this is a hack to add an ignored query parameter to the url every n milliseconds, forcing the url to reload

(I know that polling for logs isn't the ideal implementation for things, but I don't control the server I'm connecting to in this situation, and a poll would be very useful)

### CODE REVIEW

**Comment by BenMusch** [comment]
cc @helfi92 -- sorry for the tag! I just know github notifications can leave our PRs occasionally. If you have the time I'd love some feedback

**Comment by helfi92** [comment]
@BenMusch 👋 Would changing the `key` help?

```jsx
// change count every n milliseconds
<LazyLog key={count} ... />
```

This would re-create the LazyLog component.

**Comment by BenMusch** [comment]
Yeah that would work! I'd personally prefer this API but if you don't want to add this option into the component that's totally understandable

**Comment by helfi92** [comment]
Awesome. I'll close the PR but keep it in mind for the future if there is more demand. Thanks for understanding :)

**Pull request closed without merging**
