### PR TITLE
Add text option to load file from string

### PR DESCRIPTION
**Pull request by charlesverge**
This creates an option to pass a text file with <LazyLog text={textString />

### CODE REVIEW

**Comment by gajus** [comment]
Any reason this was never merged? Would be really useful to have.

**Comment by charlesverge** [comment]
@eliperelman @gajus @helfi92 I ended up not using this module but submitted the changes incase someone else wanted them and won't be maintaining this pull request.

**Comment by gajus** [comment]
What did you end up using?

**Comment by charlesverge** [comment]
A simple paginated view, the lazylog was more then what was needed

**Comment by jiapinai** [comment]
Would you please merge this submission? please, we're waiting for weeks...

**Comment by gajus** [comment]
No longer using this either. Ended up implementing our own component for this purpose.

**Comment by helfi92** [comment]
Looking into this. Apologies for the delay!

**Comment by helfi92** [comment]
I can work on fixing this. I think I know what's happening.

**Comment by helfi92** [comment]
Released in `react-lazylog@4.4.0` 🎉

**Comment by jiapinai** [comment]
thank you very much!

**Pull request merged**
